config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root 'publics#home'
  get 'pages/index'
  get 'publics/about'
  get 'publics/programme'
  get 'publics/contact'
  resources :grades
  resources :enrollements
  resources :contents
  resources :lessons
  resources :course_modules
  resources :courses
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/content.rb
# frozen_string_literal: true

class Content < ApplicationRecord
  belongs_to :lesson
end

app/controllers/contents_controller.rb
# frozen_string_literal: true

class ContentsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  before_action :set_content, only: %i[show edit update destroy]

  # GET /contents or /contents.json
  def index
    @contents = Content.all
  end

  # GET /contents/1 or /contents/1.json
  def show; end

  # GET /contents/new
  def new
    @content = Content.new
  end

  # GET /contents/1/edit
  def edit; end

  # POST /contents or /contents.json
  def create
    @content = Content.new(content_params)
    authorize! :create, @content
    respond_to do |format|
      if @content.save
        format.html { redirect_to content_url(@content), notice: 'Content was successfully created.' }
        format.json { render :show, status: :created, location: @content }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contents/1 or /contents/1.json
  def update
    authorize! :update, @content
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to content_url(@content), notice: 'Content was successfully updated.' }
        format.json { render :show, status: :ok, location: @content }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contents/1 or /contents/1.json
  def destroy
    authorize! :destroy, @content
    @content.destroy

    respond_to do |format|
      format.html { redirect_to contents_url, notice: 'Content was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_content
    @content = Content.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def content_params
    params.require(:content).permit(:title, :type, :file_path, :lesson_id)
  end
end

app/helpers/contents_helper.rb
# frozen_string_literal: true

module ContentsHelper
end

app/views/contents/_content.html.erb
<div id="<%= dom_id content %>">
  <p>
    <strong>Title:</strong>
    <%= content.title %>
  </p>

  <p>
    <strong>Type:</strong>
    <%= content.file_type %>
  </p>

  <p>
    <strong>File path:</strong>
    <%= content.file_path %>
  </p>

  <p>
    <strong>Lesson:</strong>
    <%= content.lesson_id %>
  </p>

</div>

app/views/contents/_form.html.erb
<%= form_with(model: content) do |form| %>
  <% if content.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(content.errors.count, "error") %> prohibited this content from being saved:</h2>

      <ul>
        <% content.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :type, style: "display: block" %>
    <%= form.text_field :type %>
  </div>

  <div>
    <%= form.label :file_path, style: "display: block" %>
    <%= form.text_field :file_path %>
  </div>

  <div>
    <%= form.label :lesson_id, style: "display: block" %>
    <%= form.text_field :lesson_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/contents/edit.html.erb
<h1>Editing content</h1>

<%= render "form", content: @content %>

<br>

<div>
  <%= link_to "Show this content", @content %> |
  <%= link_to "Back to contents", contents_path %>
</div>

app/views/contents/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Contents</h1>

<div id="contents">
  <% @contents.each do |content| %>
    <%= render content %>
    <p>
      <%= link_to "Show this content", content %>
    </p>
  <% end %>
</div>

<%= link_to "New content", new_content_path %>

app/views/contents/new.html.erb
<h1>New content</h1>

<%= render "form", content: @content %>

<br>

<div>
  <%= link_to "Back to contents", contents_path %>
</div>

app/views/contents/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @content %>

<div>
  <%= link_to "Edit this content", edit_content_path(@content) %> |
  <%= link_to "Back to contents", contents_path %>

  <%= button_to "Destroy this content", @content, method: :delete %>
</div>