config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root 'publics#home'
  get 'pages/index'
  get 'publics/about'
  get 'publics/programme'
  get 'publics/contact'
  resources :grades
  resources :enrollements
  resources :contents
  resources :lessons
  resources :course_modules
  resources :courses
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    else
      # cannot %i[create edit update destroy], :all
      #   can :read, :all, user_id: user.id
      cannot %i[create edit update destroy], :User
      can :read, :all
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/content.rb
# frozen_string_literal: true

class Content < ApplicationRecord
  belongs_to :lesson
end

app/models/course.rb
# frozen_string_literal: true

class Course < ApplicationRecord
  belongs_to :user
  has_many :course_modules
  has_many :enrollements
  has_many :grades
end

app/models/course_module.rb
# frozen_string_literal: true

class CourseModule < ApplicationRecord
  belongs_to :course
  has_many :lessons
end

app/models/enrollement.rb
# frozen_string_literal: true

class Enrollement < ApplicationRecord
  belongs_to :user
  belongs_to :course
end

app/models/grade.rb
# frozen_string_literal: true

class Grade < ApplicationRecord
  belongs_to :user
  belongs_to :course
end

app/models/lesson.rb
# frozen_string_literal: true

class Lesson < ApplicationRecord
  belongs_to :course_module
  has_many :contents
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # attr_accessor :role
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :lockable, :trackable

  has_many :courses
  has_many :enrollements
  has_many :grades

  enum role: %i[student instructor admin]

  after_initialize :set_default_role, if: :new_record?

  def set_default_role
    self.role ||= :user
  end

  def admin?
    self.role == 'admin'
  end
end

app/controllers/grades_controller.rb
# frozen_string_literal: true

class GradesController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  before_action :set_grade, only: %i[show edit update destroy]

  # GET /grades or /grades.json
  def index
    @grades = Grade.all
  end

  # GET /grades/1 or /grades/1.json
  def show; end

  # GET /grades/new
  def new
    @grade = Grade.new
  end

  # GET /grades/1/edit
  def edit; end

  # POST /grades or /grades.json
  def create
    @grade = Grade.new(grade_params)
    authorize! :create, @Grade
    respond_to do |format|
      if @grade.save
        format.html { redirect_to grade_url(@grade), notice: 'Grade was successfully created.' }
        format.json { render :show, status: :created, location: @grade }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @grade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grades/1 or /grades/1.json
  def update
    authorize! :update, @grade
    respond_to do |format|
      if @grade.update(grade_params)
        format.html { redirect_to grade_url(@grade), notice: 'Grade was successfully updated.' }
        format.json { render :show, status: :ok, location: @grade }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @grade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grades/1 or /grades/1.json
  def destroy
    authorize! :destroy, @grade
    @grade.destroy

    respond_to do |format|
      format.html { redirect_to grades_url, notice: 'Grade was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_grade
    @grade = Grade.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def grade_params
    params.require(:grade).permit(:user_id, :course_id, :grade)
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  before_action :authenticate_user!
  def index; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/contents_helper.rb
# frozen_string_literal: true

module ContentsHelper
end

app/helpers/course_modules_helper.rb
# frozen_string_literal: true

module CourseModulesHelper
end

app/helpers/courses_helper.rb
# frozen_string_literal: true

module CoursesHelper
end

app/helpers/enrollements_helper.rb
# frozen_string_literal: true

module EnrollementsHelper
end

app/helpers/grades_helper.rb
# frozen_string_literal: true

module GradesHelper
end

app/helpers/lessons_helper.rb
# frozen_string_literal: true

module LessonsHelper
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
end

app/helpers/publics_helper.rb
module PublicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Academy</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= render "shared/flash" %>
    <div class="container-fluid">
   <div class="row">
   <div class="col-4">
    <%= render 'shared/pages_sidebar'%>
    </div>
    <div class="col-8">
    <%= yield %>
    </div>
    </div>
    <div class="row">
      <%= render 'shared/footer'%>
    </div>
    </div>
  </body>
</html>

app/views/layouts/publics.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Academy</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
  <%= render 'shared/public_header'%>
    <%= yield %>
  <%= render 'shared/footer'%>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/shared/_flash.html.erb
<% if notice %>
  <p class="notice"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert"><%= alert %></p>
<% end %>

app/views/shared/_footer.html.erb
<div class="container">
  <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <div class="col-md-4 d-flex align-items-center">
      <a href="/" class="mb-3 me-2 mb-md-0 text-body-secondary text-decoration-none lh-1">
        <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"/></svg>
      </a>
      <span class="mb-3 mb-md-0 text-body-secondary">&copy; 2024 ACADEMIE</span>
    </div>

    <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
      <li class="ms-3"><a class="text-body-secondary" href="#"><i class="bi bi-twitter-x"></i></a></li>
      <li class="ms-3"><a class="text-body-secondary" href="#"><i class="bi bi-linkedin"></i></svg></a></li>
      <li class="ms-3"><a class="text-body-secondary" href="#"><i class="bi bi-facebook"></i></a></li>
    </ul>
  </footer>
</div>

app/views/shared/_pages_sidebar.html.erb
<div class="d-flex flex-column flex-shrink-0 p-3 text-bg-dark" style="width: 280px;"><%= link_to root_path, class: "d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none" do %> <i class="bi bi-house"></i>
  <span class="nav_name">Acceuil</span><% end %>
  <hr>
  <ul class="nav nav-pills flex-column mb-auto">
    <li class="nav-item">
      <%= link_to courses_path, class: "nav-link" do %> 
      <i class="bi bi-house"></i>
      <span class="nav_name">Cours </span>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to course_modules_path, class: "nav-link" do %> 
      <i class="bi bi-house"></i>
      <span class="nav_name">Modules</span><% end %>
    </li>
    <li class="nav-item">
      <%= link_to contents_path, class: "nav-link" do %> 
      <i class="bi bi-house"></i>
      <span class="nav_name">Contents </span><% end %>
    </li>
    <li class="nav-item">
      <%= link_to lessons_path, class: "nav-link" do %> 
      <i class="bi bi-house"></i>
      <span class="nav_name">Matiere </span><% end %>
    </li>
    <li class="nav-item">
      <%= link_to enrollements_path, class: "nav-link" do %> 
      <i class="bi bi-house"></i>
      <span class="nav_name">Inscriptions</span><% end %>
    </li>
    <li class="nav-item">
      <%= link_to grades_path, class: "nav-link" do %> 
      <i class="bi bi-house"></i>
      <span class="nav_name">Notes</span><% end %>
    </li>
    <li class="nav-item">
      <%= link_to  destroy_user_session_path, data: {turbo_method: :delete}, :class=> "nav_link" do %> 
      <i class="bi bi-box-arrow-right"></i>
      <span class="nav_name">Sortir</span><% end %>
    </li>
  </ul>
</div>

app/views/shared/_public_header.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <div class="container-fluid">
    <%= link_to "Academie", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <li class="nav-item">
          <%= link_to "Academie", root_path, class:"nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "A propos de nous" , publics_about_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Nos programmes", publics_programme_path, class: "nav-link" %>
        </li>
          <%= link_to "Tableau de bord", pages_index_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Contactez-nous", publics_contact_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>