config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root 'publics#home'
  get 'pages/index'
  get 'publics/about'
  get 'publics/programme'
  get 'publics/contact'
  resources :grades
  resources :enrollements
  resources :contents
  resources :lessons
  resources :course_modules
  resources :courses
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/lesson.rb
# frozen_string_literal: true

class Lesson < ApplicationRecord
  belongs_to :course_module
  has_many :contents
end

app/controllers/lessons_controller.rb
# frozen_string_literal: true

class LessonsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  before_action :set_lesson, only: %i[show edit update destroy]

  # GET /lessons or /lessons.json
  def index
    @lessons = Lesson.all
  end

  # GET /lessons/1 or /lessons/1.json
  def show; end

  # GET /lessons/new
  def new
    @lesson = Lesson.new
  end

  # GET /lessons/1/edit
  def edit; end

  # POST /lessons or /lessons.json
  def create
    @lesson = Lesson.new(lesson_params)
    authorize! :create, @lesson
    respond_to do |format|
      if @lesson.save
        format.html { redirect_to lesson_url(@lesson), notice: 'Lesson was successfully created.' }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lessons/1 or /lessons/1.json
  def update
    authorize! :update, @lesson
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to lesson_url(@lesson), notice: 'Lesson was successfully updated.' }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1 or /lessons/1.json
  def destroy
    authorize! :destroy, @lesson
    @lesson.destroy

    respond_to do |format|
      format.html { redirect_to lessons_url, notice: 'Lesson was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_lesson
    @lesson = Lesson.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def lesson_params
    params.require(:lesson).permit(:title, :content, :course_module_id)
  end
end

app/helpers/lessons_helper.rb
# frozen_string_literal: true

module LessonsHelper
end

app/views/lessons/_form.html.erb
<%= form_with(model: lesson) do |form| %>
  <% if lesson.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(lesson.errors.count, "error") %> prohibited this lesson from being saved:</h2>

      <ul>
        <% lesson.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_field :content %>
  </div>

  <div>
    <%= form.label :course_module_id, style: "display: block" %>
    <%= form.text_field :course_module_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/lessons/_lesson.html.erb
<div id="<%= dom_id lesson %>">
  <p>
    <strong>Title:</strong>
    <%= lesson.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= lesson.content %>
  </p>

  <p>
    <strong>Course module:</strong>
    <%= lesson.course_module_id %>
  </p>

</div>

app/views/lessons/edit.html.erb
<h1>Editing lesson</h1>

<%= render "form", lesson: @lesson %>

<br>

<div>
  <%= link_to "Show this lesson", @lesson %> |
  <%= link_to "Back to lessons", lessons_path %>
</div>

app/views/lessons/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Lessons</h1>

<div id="lessons">
  <% @lessons.each do |lesson| %>
    <%= render lesson %>
    <p>
      <%= link_to "Show this lesson", lesson %>
    </p>
  <% end %>
</div>

<%= link_to "New lesson", new_lesson_path %>

app/views/lessons/new.html.erb
<h1>New lesson</h1>

<%= render "form", lesson: @lesson %>

<br>

<div>
  <%= link_to "Back to lessons", lessons_path %>
</div>

app/views/lessons/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @lesson %>

<div>
  <%= link_to "Edit this lesson", edit_lesson_path(@lesson) %> |
  <%= link_to "Back to lessons", lessons_path %>

  <%= button_to "Destroy this lesson", @lesson, method: :delete %>
</div>